### html - 200
GET  http://130.193.37.228:9005/item/1/

###  - 404
GET  http://130.193.37.228:9005/item/122444/

###  - 200
GET  http://130.193.37.228:9005/buy/1/

###  - 404
GET  http://130.193.37.228:9005/buy/122444/

### С дисконтом и налогом - 200
POST  http://127.0.0.1:8000/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "20%",
    "items": [1,2]
}

### Без дисконта и налога - 200
POST  http://127.0.0.1:8000/order_create/
Content-Type: application/json

{
    "items": [1,2]
}

### Разные валюты - 409
POST  http://127.0.0.1:8000/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "20%",
    "items": [2,4]
}

###  - 404
POST  http://127.0.0.1:8000/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "20%",
    "items": [2,112244]
}

### html - 200
GET  http://130.193.37.228:9005/order_html/1/

### html - 404
GET  http://130.193.37.228:9005/order_html/1122444/