### html - 200
GET  http://130.193.37.228:9005/item/1/

###  - 404
GET  http://130.193.37.228:9005/item/122444/

###  - 200
GET  http://130.193.37.228:9005/buy/1/

###  - 404
GET  http://130.193.37.228:9005/buy/122444/

### С дисконтом и налогом - 200
POST  http://130.193.37.228:9005/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "20%",
    "items": [1,2]
}

### Без дисконта и налога(по умолчанию 20%) - 200
POST  http://130.193.37.228:9005/order_create/
Content-Type: application/json

{
    "items": [1,2]
}

### Не верный дисконт - 404
POST  http://130.193.37.228:9005/order_create/
Content-Type: application/json

{
    "discont": "error",
    "tax": "20%",
    "items": [1,2]
}

### Не верный налог - 404
POST  http://130.193.37.228:9005/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "error",
    "items": [1,2]
}

### Разные валюты - 400
POST  http://130.193.37.228:9005/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "20%",
    "items": [1,4]
}

###  - 404
POST  http://130.193.37.228:9005/order_create/
Content-Type: application/json

{
    "discont": "sljEVntJ",
    "tax": "20%",
    "items": [2,112244]
}

### html - 200
GET  http://130.193.37.228:9005/order_html/1/

### html - 404
GET  http://130.193.37.228:9005/order_html/1122444/