# Generated by Django 4.1.1 on 2022-09-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discont_unit', models.CharField(max_length=255, verbose_name='Скидка')),
                ('discont_link', models.CharField(max_length=255, verbose_name='Ссылка Stripe')),
            ],
            options={
                'verbose_name': 'Дисконт',
                'verbose_name_plural': 'Дисконты',
                'default_related_name': 'DiscontOrder',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя товара.')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара.')),
                ('price', models.IntegerField(verbose_name='Цена товара.')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
                'default_related_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_unit', models.CharField(max_length=255, verbose_name='Налог')),
                ('tax_link', models.CharField(max_length=255, verbose_name='Ссылка Stripe')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
                'default_related_name': 'TaxOrder',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discont', models.ForeignKey(help_text='Выберите дисконт для добавления в заказ', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.discount', verbose_name='Дисконт')),
                ('items', models.ManyToManyField(help_text='Выберите товар.', to='api.item', verbose_name='Заказ товаров.')),
                ('tax', models.ForeignKey(help_text='Выберите налог для добавления в заказ', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.tax', verbose_name='Налог')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'default_related_name': 'Order',
            },
        ),
    ]
