# Generated by Django 4.1.1 on 2022-09-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'Item', 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='discont',
            field=models.ForeignKey(blank=True, help_text='Выберите дисконт для добавления в заказ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.discount', verbose_name='Дисконт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(help_text='Выберите товар.(В админке несколько товаров через - "Ctr")', related_name='order', to='api.item', verbose_name='Заказ товаров.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Выберите налог для добавления в заказ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.tax', verbose_name='Налог'),
        ),
    ]
